/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Zeo
 */
public class JFAgenda extends javax.swing.JFrame {

    private Connection conexion;
    private Statement st;
    private PreparedStatement pst;
    private ResultSet rs;

    public void Conectar() {
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/agenda_tic32", "tic32", "Tic.32");
            st = conexion.createStatement();
            rs = st.executeQuery("Select * from contactos;");
            rs.next();
            llenarDatos();

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error 000" + err.getMessage());
        }

    }

    public void llenarDatos() {
        try {
            this.jtf_id_contacto.setText(rs.getString("id_contacto"));
            this.jtf_nombre.setText(rs.getString("nombre"));
            this.jtf_apellido_paterno.setText(rs.getString("apellido_paterno"));
            this.jtf_apellido_materno.setText(rs.getString("apellido_materno"));
            this.jtf_email.setText(rs.getString("email"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }

    public void siguienteRegistro() {
        try {
            if (!rs.isLast()) {
                rs.next();
                llenarDatos();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error 002" + ex.getMessage());
        }
    }

    public void anteriorRegistro() {
        try {
            if (!rs.isFirst()) {
                rs.previous();
                llenarDatos();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error 003" + ex.getMessage());
        }
    }

    public void primerRegistro() {
        try {
            rs.first();
            llenarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error 004" + ex.getMessage());
        }
    }

    public void ultimoRegistro() {
        try {
            rs.last();
            llenarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error 005" + ex.getMessage());
        }
    }
    
    public void habilitarCajas(){
        jtf_nombre.setEditable(true);
        jtf_apellido_paterno.setEditable(true);
        jtf_apellido_materno.setEditable(true);
        jtf_email.setEditable(true);
    }
    
    public void insertarRegistro(){
        try {
            String nombre = jtf_nombre.getText();
            String apellido_paterno = jtf_apellido_paterno.getText();
            String apellido_materno = jtf_apellido_materno.getText();
            String email = jtf_email.getText();
            
            String sql = "INSERT into contactos(nombre,apellido_paterno,apellido_materno,email)"
                    + " values(?,?,?,?);";
            
            pst = conexion.prepareStatement(sql);
            pst.setString(1, nombre);
            pst.setString(2, apellido_paterno);
            pst.setString(3, apellido_materno);
            pst.setString(4, email);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Registro insertado exitosamente");
            seleccionarTodosLosRegistros();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error 006" + ex.getMessage());
        }
        
    }
    
    public void seleccionarTodosLosRegistros(){
        try {
            String sql = "SELECT * FROM contactos;";
            pst = conexion.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.first();
            llenarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error 007" + ex.getMessage());
        }
        
    }

    /**
     * Creates new form JFAgenda
     */
    public JFAgenda() {
        initComponents();
        Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_titulo = new javax.swing.JLabel();
        jl_id_contacto = new javax.swing.JLabel();
        jtf_id_contacto = new javax.swing.JTextField();
        jl_nombre = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jtf_apellido_paterno = new javax.swing.JTextField();
        jl_apellido_paterno = new javax.swing.JLabel();
        jtf_apellido_materno = new javax.swing.JTextField();
        jl_apellido_materno = new javax.swing.JLabel();
        jtf_email = new javax.swing.JTextField();
        jl_email = new javax.swing.JLabel();
        jp_contoles_movimiento = new javax.swing.JPanel();
        jb_primer_registro = new javax.swing.JButton();
        jb_registro_anterior = new javax.swing.JButton();
        jb_registro_siguiente = new javax.swing.JButton();
        jb_ultimo_registro = new javax.swing.JButton();
        jp_controles = new javax.swing.JPanel();
        jb_nuevo = new javax.swing.JButton();
        jb_insertar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jl_titulo.setBackground(new java.awt.Color(51, 204, 255));
        jl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_titulo.setText("Agenda TIC32");
        jl_titulo.setOpaque(true);

        jl_id_contacto.setText("ID");

        jtf_id_contacto.setEditable(false);
        jtf_id_contacto.setText("jTextField1");

        jl_nombre.setText("Nombre");

        jtf_nombre.setEditable(false);
        jtf_nombre.setText("jTextField1");

        jtf_apellido_paterno.setEditable(false);
        jtf_apellido_paterno.setText("jTextField1");

        jl_apellido_paterno.setText("Apellido Paterno");

        jtf_apellido_materno.setEditable(false);
        jtf_apellido_materno.setText("jTextField1");

        jl_apellido_materno.setText("Apellido Materno");

        jtf_email.setEditable(false);
        jtf_email.setText("jTextField1");

        jl_email.setText("Email");

        jp_contoles_movimiento.setBackground(new java.awt.Color(255, 255, 255));

        jb_primer_registro.setText("|<");
        jb_primer_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_primer_registroActionPerformed(evt);
            }
        });

        jb_registro_anterior.setText("<<");
        jb_registro_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registro_anteriorActionPerformed(evt);
            }
        });

        jb_registro_siguiente.setText(">>");
        jb_registro_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registro_siguienteActionPerformed(evt);
            }
        });

        jb_ultimo_registro.setText(">|");
        jb_ultimo_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ultimo_registroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_contoles_movimientoLayout = new javax.swing.GroupLayout(jp_contoles_movimiento);
        jp_contoles_movimiento.setLayout(jp_contoles_movimientoLayout);
        jp_contoles_movimientoLayout.setHorizontalGroup(
            jp_contoles_movimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contoles_movimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_primer_registro)
                .addGap(18, 18, 18)
                .addComponent(jb_registro_anterior)
                .addGap(18, 18, 18)
                .addComponent(jb_registro_siguiente)
                .addGap(35, 35, 35)
                .addComponent(jb_ultimo_registro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_contoles_movimientoLayout.setVerticalGroup(
            jp_contoles_movimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contoles_movimientoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jp_contoles_movimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_primer_registro)
                    .addComponent(jb_registro_anterior)
                    .addComponent(jb_registro_siguiente)
                    .addComponent(jb_ultimo_registro))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jb_nuevo.setText("Nuevo");
        jb_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_nuevoActionPerformed(evt);
            }
        });

        jb_insertar.setText("Insertar");
        jb_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_insertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_controlesLayout = new javax.swing.GroupLayout(jp_controles);
        jp_controles.setLayout(jp_controlesLayout);
        jp_controlesLayout.setHorizontalGroup(
            jp_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_controlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_insertar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_controlesLayout.setVerticalGroup(
            jp_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_controlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_nuevo)
                    .addComponent(jb_insertar))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jl_apellido_materno, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_apellido_materno, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jl_apellido_paterno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_apellido_paterno, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jl_id_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jtf_id_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jp_contoles_movimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp_controles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_id_contacto)
                    .addComponent(jtf_id_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_apellido_paterno)
                    .addComponent(jtf_apellido_paterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_apellido_materno)
                    .addComponent(jtf_apellido_materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_email)
                    .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_contoles_movimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jp_controles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_registro_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registro_siguienteActionPerformed
        siguienteRegistro();
    }//GEN-LAST:event_jb_registro_siguienteActionPerformed

    private void jb_primer_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_primer_registroActionPerformed
        primerRegistro();
    }//GEN-LAST:event_jb_primer_registroActionPerformed

    private void jb_registro_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registro_anteriorActionPerformed
        anteriorRegistro();
    }//GEN-LAST:event_jb_registro_anteriorActionPerformed

    private void jb_ultimo_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ultimo_registroActionPerformed
        ultimoRegistro();
    }//GEN-LAST:event_jb_ultimo_registroActionPerformed

    private void jb_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_nuevoActionPerformed
        jp_contoles_movimiento.setEnabled(false);
        jtf_id_contacto.setText("");
        jtf_nombre.setText("");
        jtf_apellido_paterno.setText("");
        jtf_apellido_materno.setText("");
        jtf_email.setText("");
        
        habilitarCajas();
    }//GEN-LAST:event_jb_nuevoActionPerformed

    private void jb_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_insertarActionPerformed
        insertarRegistro();
    }//GEN-LAST:event_jb_insertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_insertar;
    private javax.swing.JButton jb_nuevo;
    private javax.swing.JButton jb_primer_registro;
    private javax.swing.JButton jb_registro_anterior;
    private javax.swing.JButton jb_registro_siguiente;
    private javax.swing.JButton jb_ultimo_registro;
    private javax.swing.JLabel jl_apellido_materno;
    private javax.swing.JLabel jl_apellido_paterno;
    private javax.swing.JLabel jl_email;
    private javax.swing.JLabel jl_id_contacto;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JPanel jp_contoles_movimiento;
    private javax.swing.JPanel jp_controles;
    private javax.swing.JTextField jtf_apellido_materno;
    private javax.swing.JTextField jtf_apellido_paterno;
    private javax.swing.JTextField jtf_email;
    private javax.swing.JTextField jtf_id_contacto;
    private javax.swing.JTextField jtf_nombre;
    // End of variables declaration//GEN-END:variables
}
